export const PHILIPPINE_CITIES: string[] = [
  'Angeles',
  'Antipolo',
  'Bacolod',
  'Bacoor',
  'Baguio',
  'Batangas City',
  'Biñan',
  'Butuan',
  'Cabanatuan',
  'Cagayan de Oro',
  'Calamba',
  'Caloocan',
  'Cebu City',
  'Cotabato City',
  'Dagupan',
  'Dasmariñas',
  'Davao City',
  'Dumaguete',
  'General Santos',
  'General Trias',
  'Iligan',
  'Iloilo City',
  'Imus',
  'Las Piñas',
  'Legazpi',
  'Lipa',
  'Lucena',
  'Makati',
  'Malabon',
  'Malaybalay',
  'Mandaluyong',
  'Mandaue',
  'Manila',
  'Maramag',
  'Marikina',
  'Muntinlupa',
  'Naga',
  'Navotas',
  'Olongapo',
  'Ormoc',
  'Parañaque',
  'Pasay',
  'Pasig',
  'Puerto Princesa',
  'Quezon City',
  'Roxas City',
  'San Fernando',
  'San Juan',
  'San Pedro',
  'Santa Rosa',
  'Tacloban',
  'Taguig',
  'Tagum',
  'Tarlac City',
  'Tuguegarao',
  'Valencia City',
  'Valenzuela',
  'Zamboanga City',
]
